import { GoogleGenerativeAI } from '@google/generative-ai';
import { env } from '../config/env';
import { IAssignment } from '../models/Assignment';
import { SYSTEM_PROMPT, buildUserPrompt } from './promptService';
import { z } from 'zod';

const genAI = new GoogleGenerativeAI(env.GEMINI_API_KEY);

const QuestionSchema = z.object({
  questionNumber: z.number(),
  text: z.string(),
  type: z.enum(['MCQ', 'ShortAnswer', 'LongAnswer', 'TrueFalse', 'FillBlank']),
  difficulty: z.enum(['easy', 'medium', 'hard']),
  bloomsLevel: z.enum(['remember', 'understand', 'apply', 'analyze', 'evaluate', 'create']),
  marks: z.number(),
  options: z.array(z.string()).optional(),
  expectedAnswer: z.string().optional()
});

const SectionSchema = z.object({
  title: z.string(),
  instructions: z.string().optional(),
  questions: z.array(QuestionSchema)
});

const PaperSchema = z.object({
  sections: z.array(SectionSchema)
});

export type QuestionPaperData = {
  sections: z.infer<typeof SectionSchema>[];
  rawAIResponse: string;
  generationPrompt: string;
};

export const aiService = {
  generatePaper: async (assignment: IAssignment): Promise<QuestionPaperData> => {
    const userPrompt = buildUserPrompt(assignment);
    const modelsToTry = ['gemini-3.5-flash', 'gemini-1.5-flash', 'gemini-flash-latest'];
    const combinedPrompt = `${SYSTEM_PROMPT}\n\n${userPrompt}`;
    
    let result: any;
    let lastError: any;

    for (const modelName of modelsToTry) {
      try {
        const model = genAI.getGenerativeModel({ model: modelName });
        result = await model.generateContent(combinedPrompt);
        console.log(`Successfully generated paper using model: ${modelName}`);
        break;
      } catch (error: any) {
        console.error(`Gemini API Error with model ${modelName}: ${error.message}`);
        lastError = error;
        // Wait before trying the next model to avoid instant rate limit hits
        await new Promise(res => setTimeout(res, 2000));
      }
    }
    if (!result) {
      throw lastError || new Error('Failed to generate content with all fallback models');
    }

    const rawText = result.response.text();
    
    if (!rawText) {
      throw new Error('No text generated by AI model');
    }

    let jsonString = rawText;
    let parsedData: any;

    try {
      parsedData = JSON.parse(jsonString);
    } catch (e) {
      // Fallback regex extraction if pure parse fails
      const match = rawText.match(/\{[\s\S]*\}/);
      if (match) {
        try {
          parsedData = JSON.parse(match[0]);
        } catch (innerE) {
          throw new Error('Failed to parse JSON extracted via regex from AI response');
        }
      } else {
        throw new Error('AI response did not contain valid JSON block');
      }
    }

    try {
      // Validate with Zod
      const validData = PaperSchema.parse(parsedData);
      
      return {
        sections: validData.sections,
        rawAIResponse: rawText,
        generationPrompt: userPrompt
      };
    } catch (zodError) {
      console.error("Zod Validation Error on AI Response:", zodError);
      throw new Error(`Invalid schema returned by AI: ${(zodError as Error).message}`);
    }
  }
};
